### ISSUE TITLE
The extension stuck scrolling down 

### ISSUE THREAD

**Issue by AMMARmms** [AlkTheOrg/imdb-watchlist-randomizer#1]
### The extension continued to scroll down even after reaching its target (the last element in the watchlist).

I reviewed the source code to identify the source of the problem. I found that the issue lies with the if condition in the "getMultimedias.js" file. The condition is always false, causing the code to remain stuck at the (else) statement. 
I then attempted to identify the issue within the if condition. Upon replacing the querySelectorAll's argument for (**allTitles**) variable from **.ipc-title-link-wrapper'** to **".ipc-metadata-list-summary-item"**, the code worked as intended. Additionally,I also made minor changes to a few lines of code to address the issues that appeared following the aforementioned change.  

I've Uploaded the edited "getMultimedias.js" file , and I've added these *** and +++ symbols before some lines in the file to indicate that it's been edited or that it's a new line. Here's the [link](https://drive.google.com/file/d/1gmdmV3YOw0OCDbRfGp2Pbe6fsOW7CIB8/view?usp=sharing).
Please review it, add your touch and update the extension on chromewebstore as soon as possible. @AlkTheOrg

**Comment by AlkTheOrg** [comment]
> I've Uploaded the edited "getMultimedias.js" file , and I've added these *** and +++ symbols before some lines in the file to indicate that it's been edited or that it's a new line. Here's the [link](https://drive.google.com/file/d/1gmdmV3YOw0OCDbRfGp2Pbe6fsOW7CIB8/view?usp=sharing).

This is exactly what git is for. If you want others to review your code and collaborate, then please open a pull request.

> Upon replacing the querySelectorAll's argument for (allTitles) variable from .ipc-title-link-wrapper' to ".ipc-metadata-list-summary-item", the code worked as intended.

This doesn't explain the reasoning. Every `.ipc-metadata-list-summary-item` element contains a `.ipc-title-link-wrapper` element, so the root cause should not be it.

I was able to reproduce an error in the `isInView` logic yesterday. If the page scrolls too far (different users have different content in the footer, such as a login link), the last title may not be visible. So, rather than checking if the target is in view, I should check if the page has already scrolled over it. However, this should not block you. When the `Scan and Randomize` process is complete, do not close the extension. Simply scroll up until you see your last element, and your randomized content should appear. Temporary solution until I can resolve the issue I mentioned.

**Comment by AMMARmms** [comment]
> This doesn't explain the reasoning. Every .ipc-metadata-list-summary-item element contains a .ipc-title-link-wrapper element, so the root cause should not be it.

I opened a **135-title** watchlist page and ran the code on it. I added a line to display the content generated from .ipc-title-link-wrapper on the console. There was another line for the content of .ipc-metadata-list. 
I found that **.ipc-metadata-list-summary-item** generated an array of **135** elements as expected, but **.ipc-title-link-wrapper** generated an array of **137** elements. There were two extra elements in the array.
 The first is "your exports." If you've exported a list before, you'll see this. The second extra element is the name of the episode. If you've watchlisted an episode  before, you'll see this. The series name and the episode name considered as 2 different elements in the array. I have attached 3 **screenshots** to make it more obvious.

![1](https://github.com/AlkTheOrg/imdb-watchlist-randomizer/assets/110132520/878bf4f7-49ad-4c87-9a0c-5b828f20d8c3)
![2](https://github.com/AlkTheOrg/imdb-watchlist-randomizer/assets/110132520/c9aa54f7-5ac3-4165-9d60-c5cbd545e041)
![3](https://github.com/AlkTheOrg/imdb-watchlist-randomizer/assets/110132520/2058dad0-0f19-4da0-b26a-c79f2cbee847)
Based on that you shouldn't use **.ipc-title-link-wrapper** to extract movie titles. This sometimes adds unwanted elements that may affect the code's behavior. 

>  I was able to reproduce an error in the isInView logic yesterday. If the page scrolls too far (different users have different content in the footer, such as a login link), the last title may not be visible. So, rather than checking if the target is in view, I should check if the page has already scrolled over it

This hasn't happened to me much, but it'd be a great idea to fix it.

**Comment by AlkTheOrg** [comment]
> Based on that you shouldn't use .ipc-title-link-wrapper to extract movie titles. This sometimes adds unwanted elements that may affect the code's behavior.

I see. Thanks for the detailed explanation! I will update the code soon.

If you'd like me to check the minor changes you made as well, please open a PR as it is very hard to understand what's going on from your drive file.

**Comment by AMMARmms** [comment]
> If you'd like me to check the minor changes you made as well, please open a PR as it is very hard to understand what's going on from your drive file.

Ok, I'll do that asap.
